version: '3.8'
services:
  app:
    build:
      context: ./app
    deploy:
      replicas: 3
    networks:
      - backend_network

  nginx-lb:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend_network

networks:
  backend_network:
